#!/usr/bin/env bash
bin=./node_modules/.bin
rm -rf dist
mkdir -p dist/qualification dist/ticket
mkdir -p dist/apply/img/
echo "build lib script ..."
$bin/lsc -cbp --no-header src/apply/lib.ls > dist/apply/lib.js
$bin/uglifyjs dist/apply/lib.js -m -c > dist/apply/lib.min.js
echo "build pug files to html files ..."
echo "index.pug ..."
$bin/srcbuild-pug src/apply/index.pug > dist/apply/index.html
echo "qualification/user.pug ..."
./node_modules/.bin/srcbuild-pug src/qualification/user.pug > dist/qualification/user.html
echo "ticket/user.pug ..."
./node_modules/.bin/srcbuild-pug src/ticket/user.pug > dist/ticket/user.html
echo "ticket/all.pug ..."
./node_modules/.bin/srcbuild-pug src/ticket/all.pug > dist/ticket/all.html

# building customized @makeform/image
echo "widgets/image/index.pug ..."
./node_modules/.bin/srcbuild-pug src/apply/widgets/image/index.pug -o dist/apply/widgets/image/index.html

# building customized @makeform/upload
echo "widgets/upload/index.pug ..."
./node_modules/.bin/srcbuild-pug src/apply/widgets/upload/index.pug -o dist/apply/widgets/upload/index.html

echo "copy image files"
cp -f src/apply/img/* dist/apply/img/
echo "copy dist into static folder..."
rm -rf web/static/assets/lib/block/main/
mkdir -p web/static/assets/lib/block/main/
cp -R dist/* web/static/assets/lib/block/main/
echo "done."
